from aiogram.fsm.state import StatesGroup, State


class RegistrationStates(StatesGroup):
    waiting_for_name = State()
    waiting_for_role = State()
    waiting_for_object = State()
    waiting_for_system = State()
    waiting_for_subsystem = State()
    waiting_for_type_of_work = State()
    waiting_for_spent_time = State()
    waiting_for_notes = State()
    waiting_for_more = State()
    waiting_for_password = State()
    waiting_for_info = State()
    waiting_for_notification_chose = State()
    waiting_for_hour = State()
    waiting_for_minute = State()
    waiting_for_admin_chose = State()
    waiting_for_admin_table = State()
    waiting_for_admin_diagram = State()
    waiting_for_admin_keyboard_choose = State()
    waiting_for_way_to_edit_keyboard = State()
    waiting_for_create_button = State()
    waiting_for_delete_button = State()
    waiting_for_same_object = State()
    waiting_for_obj_what_to_do = State()
    waiting_for_tap_to_hide_keyboard = State()
    waiting_for_tap_to_add_button = State()
    waiting_for_tap_to_delete_button = State()
    waiting_for_extra = State()
    waiting_for_period = State()
    waiting_for_date = State()
    waiting_for_date_period = State()
